"""Manufacturing report generation tools."""

import json
from datetime import datetime
from pathlib import Path
from datapizza.tools import tool
from elfactory.tools.state_tools import active_gifts, current_gift_id


@tool
def generate_manufacturing_report(report_path: str = None) -> str:
    """
    Generate a detailed manufacturing report listing all components and collaborating agents.

    Args:
        report_path: Optional custom path to save the report (defaults to logs/reports/{gift_id}_report.md)

    Returns:
        Path to the generated report file
    """
    gift_id = current_gift_id.get()
    state = active_gifts.get(gift_id)

    if not state:
        return "Error: No active gift project found"

    if not report_path:
        reports_dir = Path("logs/reports")
        reports_dir.mkdir(parents=True, exist_ok=True)
        report_path = str(reports_dir / f"{gift_id}_report.md")

    report_lines = []
    report_lines.append(f"# Manufacturing Report - Gift {gift_id}")
    report_lines.append(f"\n**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"\n**Status:** {state.status}")
    report_lines.append("\n---\n")

    report_lines.append("## Child Information")
    report_lines.append(f"- **Name:** {state.child_info.name if state.child_info else 'Unknown'}")
    report_lines.append(f"- **Age:** {state.child_info.age if state.child_info else 'Unknown'}")
    report_lines.append(f"- **Location:** {state.child_info.location if state.child_info else 'Unknown'}")
    report_lines.append("\n---\n")

    report_lines.append("## Gift Request")
    report_lines.append(f"\n{state.gift_request}")
    report_lines.append("\n---\n")

    report_lines.append("## Components Created")
    if state.components:
        report_lines.append(f"\n**Total Components:** {len(state.components)}\n")
        for i, component in enumerate(state.components, 1):
            report_lines.append(f"\n### {i}. {component.id}")
            report_lines.append(f"- **Type:** {component.type}")
            report_lines.append(f"- **Material:** {component.material}")
            report_lines.append(f"- **Dimensions:** {component.dimensions}")
            report_lines.append(f"- **Created by:** {component.created_by}")
            report_lines.append(f"- **Status:** {component.status}")
            if component.details:
                report_lines.append(f"- **Details:** {component.details}")
    else:
        report_lines.append("\n*No components registered*")

    report_lines.append("\n\n---\n")

    report_lines.append("## Collaborating Agents")
    agents = set()
    for component in state.components:
        if component.created_by:
            agents.add(component.created_by)

    for entry in state.manufacturing_log:
        if entry.agent:
            agents.add(entry.agent)

    agents = sorted(list(agents))
    report_lines.append(f"\n**Total Agents:** {len(agents)}\n")
    for agent in agents:
        report_lines.append(f"- {agent}")

    report_lines.append("\n\n---\n")

    report_lines.append("## Manufacturing Log")
    if state.manufacturing_log:
        report_lines.append(f"\n**Total Actions:** {len(state.manufacturing_log)}\n")
        for i, entry in enumerate(state.manufacturing_log, 1):
            timestamp = entry.timestamp
            agent = entry.agent
            action = entry.action
            details = entry.details
            report_lines.append(f"\n{i}. **[{timestamp}]** {agent} - {action}")
            if details:
                report_lines.append(f"   - {details}")
    else:
        report_lines.append("\n*No actions logged*")

    report_lines.append("\n\n---\n")

    if state.issues:
        report_lines.append("## Issues Reported")
        report_lines.append(f"\n**Total Issues:** {len(state.issues)}\n")
        for i, issue in enumerate(state.issues, 1):
            report_lines.append(f"\n{i}. **[{issue.severity.upper()}]** {issue.reported_by}")
            report_lines.append(f"   - {issue.description}")
            report_lines.append(f"   - *Reported at: {issue.timestamp}*")

    report_lines.append("\n\n---\n")
    report_lines.append("\n*Report generated by Elfactory Manufacturing System*\n")

    report_content = "\n".join(report_lines)

    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report_content)

    state.log_action(
        agent="report_generator",
        action="generate_report",
        details=f"Manufacturing report saved to: {report_path}"
    )

    return f"✓ Manufacturing report generated successfully: {report_path}"
